#include<stdio.h>
#include<conio.h>
void main()
{
	int x=9,y=4,z,a,s,b;
	clrscr();
	z=x+y;
	printf("z=%d",z);
	a=x-y;
	printf("\na=%d",a);
	s=x*y;
	printf("\ns=%d",s);
	b=x/y;
	printf("\nb=%f",b);
	getch();

}
#include<stdio.h>
#include<conio.h>
void main()
{
	int x=9,y=4,z,a,b;
	float c;
	clrscr();
	z=x+y;
	printf("z=%d",z);
	a=x-y;
	printf("a=%d",a);
	b=x*y;
	printf("b=%d",b);
	c=x/y;
	printf("c=%f",c);
	getch();
}